name: video2ascii_flutter
description: "Real-time video to ASCII art converter for iOS"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0-217.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.9.2
  image_picker: ^1.1.2
  provider: ^6.1.2
  file_picker: ^8.1.6
  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
